export const skills_data = [
    {
        id:1,
        title:'HTML',
        img_src:"images/html-logo.png"
    },
    {
        id:2,
        title:'CSS',
        img_src:'images/css-logo.png'
    },
    {
        id:3,
        title:'JavaScript',
        img_src:'images/JS-logo.png'
    },
    {
        id:4,
        title:'SQL',
        img_src:'images/mysql_logo.png'
    },
    {
        id:5,
        title:'Python',
        img_src:'images/python_logo.png'
    },
]